### ISSUE TITLE
Volume bar always visible

### ISSUE THREAD

**Issue by Brilon314** [ytmdesktop/ytmdesktop#1006]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

An option to make this control always visible.
![image](https://user-images.githubusercontent.com/5781049/180046696-c01e0863-6dc6-42f8-abce-8a230fb36a1a.png)

**Comment by Hershey025** [comment]
you can do it even now by going to custom theme enable it then, click on the pencil icon and add this code - 
ytmusic-player-bar #right-controls #volume-slider {
  opacity: 0.9 !important;
  pointer-events: initial !important;
}
Copy and paste this code and then, click  on the red icon on the down right to save and then restart the app to see the change.
you will see volume bar will always be visible.
Hope it helps.

**Comment by Brilon314** [comment]
Thanks man, my life it's a little better thanks to you.

**Comment by Hershey025** [comment]
Always Welcome bro

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

This feature is now natively in YTMDv2 as well :)
