### ISSUE TITLE
Can't sign in, Browser or app may not be secure 

### ISSUE THREAD

**Issue by WildFearless** [ytmdesktop/ytmdesktop#1017]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Ive read the old thread about it 1 year ago and it still like nobody had a real fix. So are you guys going to fix this?

### Expected Behavior

Letting me log in?

### Steps To Reproduce

open the app, click on sign in, email, then nothing

### YTMDesktop

lastest

### OS

Windows

### OS Version

10

### Arch

x86

### Installation way

exe

### Anything else?

I mean it seems like the other issue was closed without a resolution, and i'd like to have rich pressence on discord so

**Comment by TarasKucher** [comment]
Fixed in a pre-released version 1.1.14, it's available here in Assets section
https://github.com/ytmdesktop/ytmdesktop/releases/tag/1.14.2

**Comment by bigstusexy** [comment]
Hello, 

Okay, all of the following was negated by me using a proxy but I'm leaving it as it may lead to something.  I know the firewall isn't inspecting HTTPS (yet), only inspecting HTTP and there is nothing to block, I'm not web filtered so I'm not sure why the proxy worked for gmail accounts, it just puts me around the firewall and would give me  a different public IP address. 


_I'd like to add that I have the same issue.  Now I did download the 1.14.2 update for windows (patched) probably a few weeks after it was released and that worked just fine at home.  Now I'm using the same package and I'm trying at work and it gives the error as stated after putting in my username and pressing Next.   It's not the network messing with or blocking anything at work.  I'd know cause I'm the network admin. 

Oddly... if I try my G-Suite email, it asks for the password.  I tried another gmail address and I get the not secure message._

**Comment by rxversedcode** [comment]
using a vpn worked for me

**Comment by kutwa** [comment]
> using a vpn worked for me (specifically pia but any should work)

Worked with vpn, thanks!

**Comment by bigstusexy** [comment]
I don't have the skills to verify this, but I'm wondering if some addresses may have been triggered for more security checks by Google, which this program cannot pass. 

I know for me at work we have hundreds of machines that connect through the one address, then if you're using the web filtering you appear to be from another address with probably hundreds of thousands of other devices and when doing so there are times where it will be flagged by Google as suspicious and you'll have to either wait for it to clear or somethings we have to reCAPATCHA. I'm wondering if this is similar but a lower step.  Unfortunately, this is super secrete sauce stuff they won't tell anyone about.

**Comment by doubledge-spec** [comment]
> Fixed in a pre-released version 1.14.2, it's available here in Assets section https://github.com/ytmdesktop/ytmdesktop/releases/tag/1.14.2

still have this issue...

**Comment by eturk1** [comment]
Long-term solution appears to be
   "Switch to use browser-based OAuth" as noted on the "learn more" link of the error.
<img width="539" alt="image" src="https://user-images.githubusercontent.com/525280/188219674-e7391d26-c8e6-4836-8821-575c4f487b9d.png">
It's a security risk to login via an in-app browser where the user can't verify their login is not being hijacked.

Coding change: 
   "This authorization flow is similar to the one used for web server applications. The main difference is that installed apps must open the system browser and supply a local redirect URI to handle responses from Google's authorization server."
https://developers.google.com/identity/protocols/oauth2/native-app

@NovusTheory & @adlerluiz 
I saw that you had commented on other OAuth requests. Do you know how to open a system browser window for OAuth instead of an embedded window? Or, is electron limited so this can never be done?

**Comment by jlink-home** [comment]
I'm not sure if there is any plans currently in the works to handle this but it seems that this link on stack overflow might have what you need to do in order to get login working long-term.
[https://stackoverflow.com/questions/66769003/how-can-i-use-google-sign-in-inside-of-an-electron-desktop-application](https://stackoverflow.com/questions/66769003/how-can-i-use-google-sign-in-inside-of-an-electron-desktop-application)

**Comment by NovusTheory** [comment]
What you're all not aware of is that we aren't doing OAuth and we can't do OAuth. The app is merely served like a browser but specifically for YTM. We cannot delegate logins outside the app as there is no OAuth happening in the first place.

**Comment by eturk1** [comment]
Are you saying that we'll never be able to login to YouTube music because of the new enhanced security requirement from Google? Thus this is only an app for non-premium users, no playlists, etc?

> What you're all not aware of is that we aren't doing OAuth and we can't do OAuth. The app is merely served like a browser but specifically for YTM. We cannot delegate logins outside the app as there is no OAuth happening in the first place. I understand the security concerns with that and it's not ideal, but this is the way these types of apps have worked and always have worked.

**Comment by NovusTheory** [comment]
> Are you saying that we'll never be able to login to YouTube music because of the new enhanced security requirement from Google? Thus this is only an app for non-premium users, no playlists, etc?

No, this is an issue that's is being actively looked at and I'm going to close this issue as a duplicate of #866 to keep discussion centralized there. :)

**Comment by eturk1** [comment]
#866 was locked with last comment in March, 6 months ago. 
That keeps us from posting help like StackOverflow link above.

Might you keep us updated in #866 please? Allow posting again there? :)  
Really appreciate your efforts!

----------
If not going to use OAuth, the stackoverflow link above can't be implemented, a hack to keep in-app login is being tried? 
(I used VPN country change hack myself). 
Concern is Google doesn't want in-app logins that hide URL and can hijack our logins. OAuth (link above) seems to be only long-term solution?

> 
> No, this is an issue that's is being actively looked at and I'm going to close this issue as a duplicate of #866 to keep discussion centralized there. :)

**Comment by NovusTheory** [comment]
> Might you keep us updated in https://github.com/ytmdesktop/ytmdesktop/issues/866 please? Allow posting again there? :)
Really appreciate your efforts!

That might be up to Ali to unlocking if needed since they did that and have mostly taken charge on the issue.

I might peek at this issue if you have anything to contribute but I'm not going to make promises as I closed this to keep it triaged to #866. You can always [join the Discord server](https://discord.gg/av582qYG) to contribute anything and it will be noticed.
