### ISSUE TITLE
Feature Request : Ability to download your playlist/library ?

### ISSUE THREAD

**Issue by c0der4t** [ytmdesktop/ytmdesktop#103]

**Comment by adlerluiz** [comment]
YouTube Music doesn’t provide a way to download the songs on your computer, just now the ones you’ve uploaded.

**Comment by mingjun97** [comment]
Using the API exposed by AudioOnly Youtube (I investigaed before) could help you download music from Youtube music. But YTMDesktop doesn't support play local files, which means you can only play the offlined file using your local player. If you guys think this kind of feature will helpful, let us know and we will think to add it.

**Comment by TotalChris** [comment]
Standard YouTube downloaders can't download personally-uploaded music because the songs themselves are private to your account. I'm sure providing an API key to a request would work, but I didn't get this technical.

As far as other download functionality, we want to try to not get on YouTube's bad side, and integrating yotubedl would probably do that. We can argue and prove that user-uploaded tracks are legal property of the uploader, and can be downloaded, but public tracks are a big no-no.
