### ISSUE TITLE
Cannot connect to PC from remote

### ISSUE THREAD

**Issue by MKstudio-Tech** [ytmdesktop/ytmdesktop#1036]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

From all of sudden (literally was working yesterday) I cannot connect to PC from remote app. "Failed to connect with 192.xxx.xxx.xxx" Sometimes it connects, but only displays "Ready to play".

### Expected Behavior

I expect it to be working normally.

### Steps To Reproduce

1. Download app
2. Download remote
3. Try to connect

### YTMDesktop

v1.14.2

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
