### ISSUE TITLE
Lyrics won't load

### ISSUE THREAD

**Issue by Typowabrzozaa** [ytmdesktop/ytmdesktop#1037]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Lyrics won't load, says "loading..."
![image](https://user-images.githubusercontent.com/109311372/193797894-dd281f80-a1c4-4899-8046-6e758df4c8e7.png)

### Expected Behavior

lyrics

### Steps To Reproduce

1. Click a note on main page while you are listening a song 

### YTMDesktop

1.14.2

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by bookofiyi** [comment]
I have the same issue

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
