### ISSUE TITLE
Play and Pause RPC icons are barely visible in Discord Light Theme

### ISSUE THREAD

**Issue by gabuch2** [ytmdesktop/ytmdesktop#1039]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

The smaller icons when playing or pausing a song are barely visible when Discord is using light theme, this is due them being white with a transparent background, as seen in this image.

![image](https://user-images.githubusercontent.com/5295686/195240387-a0c7e8e8-d6c6-48dd-88ac-bf135ee8e237.png)

### Expected Behavior

Proposed solutions for this are

- Just not display playback status
- Use opaque icons (I believe using YTM's icon color palette would fit)

### Steps To Reproduce

- Download ytmdesktop pre-release
- Enable Discord RPC

### YTMDesktop

v1.14.2

### OS

Linux

### OS Version

Ubuntu 22.04.1 LTS

### Arch

x64

### Installation way

AppImage

**Comment by Alipoodle** [comment]
I would need to re-create the application we use for the RPC for this 😅
But yea.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

This is has been fixed with adding a shadow.
Additionally we have a Developer note included in the source for a alternative Black with a white shadow if the user wishes to build their own version which works better for light mode.

Dark/Custom:
![image](https://github.com/ytmdesktop/ytmdesktop/assets/17199186/84875ec5-b8ed-4ebd-977e-412c03021a53)
![image](https://github.com/ytmdesktop/ytmdesktop/assets/17199186/3c734b53-f32c-4841-9f5f-9e7c7d501072)
