### ISSUE TITLE
Playback switches to another audio output when the app advances to a new song

### ISSUE THREAD

**Issue by valipod** [ytmdesktop/ytmdesktop#1041]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I have headphones set as default output, and Youtube Music Desktop set to play on speakers. After updating to 1.4.2 the app switches to the default (headphones) output almost every time it advances to a new song. The tray icon still displays the output to be Speakers, but the sound goes through the Headphones. If I just select Speakers again, it redirects to Speakers. Until a new song starts. I am using eartrumpet to manage the audio interfaces, this should though have any effect here.

### Expected Behavior

Of course, expected is that the output stays as configured.

### Steps To Reproduce

Suggested steps:
1. set the audio to something other than default
2. the audio should switch to the default output when a new song starts.

### YTMDesktop

1.4.2-patched

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Gus-The-Forklift-Driver** [comment]
Same issue with Voicemeeter, altho not on every songs (it feels random).

**Comment by DMCroww** [comment]
Same issue with VoiceMeeter
While YTM is set to use secondary (AUX Input) of voicemeeter, it almost 'randomly' switches to using windows default device. 

What I've noticed so far is that this happens only while the app is in the background, and mostly when it has to switch from video mode to audio only due to 'video' portion not being available. 

Selecting the audio device 2-3 times again fixes it for 'some' random time, untill it does it again after about 3-4 hours of playback (?memory unloading?)

Happens on two separate computers with different OS versions:

**Desktop:**
OS: Win10 Pro 21H2
CPU: Intel i3-10100F
Ram: 16GB

**Laptop:**
OS: Win7 Ultimate
CPU: Intel i3-2330M
Ram: 4GB

Both computers have app **v1.13.0** installed using .exe

**Comment by robolivable** [comment]
Issue present for me also (v1.13.0)

System info:
CPU: Intel i7-9700K
RAM: 32GB
OS: Windows 10 Pro 64bit (version/build 21H2/19044.2846)

YT Music app installed using the setup tool.

**Comment by ideasculptor** [comment]
Add me to the list. I send music to my headphones so that I don't stream music without rights to it, but this app insists on switching to the default audio of my system all the time. It is tremendously frustrating.

**Comment by Gus-The-Forklift-Driver** [comment]
I seems that having the current view to the player (album cover to the left, playlist to the right), does not change the audio source. Changing to an other view seems to roll back the audio ouput change.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
