### ISSUE TITLE
Add custom css custom path.

### ISSUE THREAD

**Issue by Goxore** [ytmdesktop/ytmdesktop#1045]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

I want to change css file of the app programatically, but cannot find it in my filesystem. Please allow adding custom file path to read css from.

**Comment by A-Matt** [comment]
Why can you not just update the file automatically 🤔

**Comment by Goxore** [comment]
I don't know where it is located. I installed the program with flatpak and can't seem to find it anywhere

**Comment by mingjun97** [comment]
https://stackoverflow.com/questions/147500/is-it-possible-to-include-one-css-file-in-another

I guess the `@import` could meet your requirement. Just put the URL for your CSS file in the customize theme injection. Note that there might be some URL scheme mismatch problem, i.e. `https://` vs. `file://` which prevents you from loading CSS from the file system, but there should be a workaround for it.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

YTMDv2 now uses a chosen file instead of a Specific file.
it should automatically update if you make an edit in the file as well :)
