### ISSUE TITLE
Add to library option not showing

### ISSUE THREAD

**Issue by Hershey025** [ytmdesktop/ytmdesktop#1053]
### Consent

- [x] I verified that there is no open/closed issue for the same subject.
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

whenever i play a song i see a like, dislike and add to playlist option but add to library option is not showing. I tested this on 1.13.0 and 1.14.2. I saw this issue in both versions.

https://user-images.githubusercontent.com/94620635/203926370-643fb702-d191-47b8-9ca6-48a460e7dec2.mp4

### Expected Behavior

It should show the add to library option with the other options.

### Steps To Reproduce

go to ytm desktop
go to settings
then appearance
check if the add to library option is enabled.
then close the settings and play a song.

### YTMDesktop

v1.13.0, v1.14.2

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
