### ISSUE TITLE
Error upon startup

### ISSUE THREAD

**Issue by pdario** [ytmdesktop/ytmdesktop#1054]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When launching YTMD this appears:

[Edited]

I don't know if these are related, but this is how I see settings page

![image](https://user-images.githubusercontent.com/5813131/203973247-a4743f00-463a-46e8-9fae-359dec8335d3.png)

### Expected Behavior

No errors and labels showing

### Steps To Reproduce

Start app and go to settings

### YTMDesktop

1.14.2

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

exe

**Comment by Hershey025** [comment]
This issue seems to be  a dup of #978. This issue has already been reported.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
