### ISSUE TITLE
last.fm login popup isn't loading

### ISSUE THREAD

**Issue by DashDF** [ytmdesktop/ytmdesktop#1059]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

it very simply loads indefinitely

### Expected Behavior

to be able to log in and connect it

### Steps To Reproduce

settings, integrations, last fm scrobbler.. no workie

### YTMDesktop

1.14.2-3

### OS

Arch linux

### OS Version

linux 6.0.11

### Arch

x64

### Installation way

AUR package

**Comment by jamgregory** [comment]
I've just tried this with the code directly from GitHub, and while it seemingly asks you to enter your username and password, clicking the 'Save and authorise' button does appear to open the popup for me, at which point I can sign into last.fm as expected.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
