### ISSUE TITLE
UI Actions: Add to playlist button stopped working and it's icon now doesn't match the corresponding button on the right click menu

### ISSUE THREAD

**Issue by Marte77** [ytmdesktop/ytmdesktop#1063]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

UI action shortcut to add to playlist doesn't do anything.

### Expected Behavior

Show menu to add song to a playlist

### Steps To Reproduce

1. Activate "Show add to playlist" under Settings-> Appearance-> UI Actions
2. With a song playing, click on the add to playlist button that now shows next to the song

### YTMDesktop

v1.14.2

### OS

MacOS Ventura

### OS Version

13.1

### Arch

x64

### Installation way

.dmg

**Comment by lcfrederico** [comment]
Mine is with the same problem... I'm Using Windows Version (1.14.2 but the previous 1.13.0 version had the same behaviour earlier too)

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
