### ISSUE TITLE
stuck on installation

### ISSUE THREAD

**Issue by elonmuzg** [ytmdesktop/ytmdesktop#1070]
### Consent

- [x] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

After uninstalling and deleting ytm folder. Cant install program back beacouse installer gets stuck( i wanted to do reinstallation to try fixing issue with signing in after changing password on google.)

![obraz_2023-01-07_200841989](https://user-images.githubusercontent.com/122176589/211166685-03e5d428-2bf7-49be-afb9-35439f9ebc2d.png)

installation from cmd doesnt suceed too(exit code:5)

![image](https://user-images.githubusercontent.com/122176589/211167103-4a1dda7e-ecf4-46aa-b3e3-cf54c84bff4d.png)

### Expected Behavior

installer sucseeds in installing the app

### Steps To Reproduce

1. open installer normally/as administrator
2. installer stuck on " wait for installation ending"

### YTMDesktop

1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

YouTube-Music-Desktop-App-Setup-1.13.0.exe

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
