### ISSUE TITLE
Rainmeter's WebNowPlaying has been redone/updated

### ISSUE THREAD

**Issue by Novadestin** [ytmdesktop/ytmdesktop#1098]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Hello to whomever reads this, I was browsing around and came across [this older post](https://github.com/ytmdesktop/ytmdesktop/issues/317#issuecomment-966482001) and thought I'd let you guys know that the WebNowPlaying plugin has been given a redux. 

I'm not sure if this will require any updating to ytmdesktop in order to keep things working, but at least now you'll be aware if any issues do come up. 

### Solution

Links:

[Original plugin](https://github.com/tjhrulz/WebNowPlaying) by tjhrulz

[New Plugin](https://github.com/keifufu/WebNowPlaying-Redux-Rainmeter) by keifufu and tjhrulz

### Anything else?

Keep up the good work :)

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
