### ISSUE TITLE
Asus rog strix flare II animate media keys not working

### ISSUE THREAD

**Issue by akabakass** [ytmdesktop/ytmdesktop#1114]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

The media keys on my Asus ROG Strix Flare II animate keyboard do not work in the app

### Expected Behavior

Media keys should function as stated.

### Steps To Reproduce

    Open App
    Play Music
    Try Using Media Keys
    Nothing happen

### YTMDesktop

1.14.2

### OS

ubuntu

### OS Version

 22.04

### Arch

x64

### Installation way

build from sources

### Anything else?

xev does not show them as x86Play/stop/next dbus thingy, this might be related
there was an issue #279 refering to a previous version of the keyboard, but the issue was for windows
thx for the help

**Comment by akabakass** [comment]
I've seen you have added more info needed tag, what else do you want me to provide?

**Comment by akabakass** [comment]
Ok, fair enough, please tell me if there is anything I can provide or try for you

**Comment by Alipoodle** [comment]
Worth going to sites like: https://keyboardchecker.com to see what key gets registered when you click on the media keys.
![image](https://github.com/ytmdesktop/ytmdesktop/assets/17199186/0a3a5d26-bfda-4400-a801-6247a083e19d)

Not sure how Ubuntu and the likes have their media integration, as we only provide MPRIS for Linux to handle stuff.
Curious to see if v2 also has this issue as we are using Electron/Chromium's native Media Handler for that rather than custom doing our own integration.

**Comment by akabakass** [comment]
After more digging on my side, xev was returning weird things.
 it turns out it was not a ytmd issue, but I had some old binding in my I3 config which where catching the media keys.
Sorry about that, It works like a charm now
