### ISSUE TITLE
Unwanted Play/Pause Priority 

### ISSUE THREAD

**Issue by helpnoob** [ytmdesktop/ytmdesktop#1122]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Coming from the Spotify Win11 app, I could be watching a video on my web-browser and use the play/pause media keys on my keyboard to play/pause the active video. 
With YTMDesktop, regardless of whatever application im using, it takes priority. 

### Expected Behavior

Use play/pause keys and pauses current active task (i.e. youtube video in chrome). 
If not watching video in chrome, it controls YTMDesktop. \
Perhaps unbinding play/pause in the shortcuts settings and letting windows decide would resolve the issue.

### Steps To Reproduce

1. Have YTMDesktop running 
2. Go on Youtube.com and watch video in web-browser 
3. Try using play/pause button on video
4. YTMDesktop starts or stops playing music 

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
