### ISSUE TITLE
Rearrange the song title in Miniplayer

### ISSUE THREAD

**Issue by gokulg6963** [ytmdesktop/ytmdesktop#1129]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

While using Miniplayer mode, the **song title** is not aligned to the miniplayer size as it touching the borders when the title is long and the UI of the miniplayer need some improvement. It would be appreciable if we implement different layout for the miniplayer. The current miniplayer is in square size only.

**Comment by Alipoodle** [comment]
Inside of Beta there is an alternative layout which is similar to YTM's current layout with Album art on the left and Track/Artist on the right.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
