### ISSUE TITLE
Terminal spams `error isAdvertisement` 

### ISSUE THREAD

**Issue by HardoMX** [ytmdesktop/ytmdesktop#1143]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Especially when starting a new song, but sometimes just randomly, the terminal used to start YTMDesktop spams out `error isAdvertisement`

### Expected Behavior

Possibly showing the error once, not  hundreds

### Steps To Reproduce

1. Start YTMDesktop with `yarn start --no-sandbox` (This is the only way it starts currently on Linux #1097)
2. Start or change a song, or sometimes just wait

### YTMDesktop

Latest master

### OS

Arch

### OS Version

N/A

### Arch

x64

### Installation way

yarn from source repo

### Anything else?

As I mentioned in the steps to reproduce, to get it to start at all on Linux, you need to add the `--no-sandbox` flag after `yarn start`

I also have a premium subscription, if that could somehow affect things

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
