### ISSUE TITLE
autofocus default for up-down arrows

### ISSUE THREAD

**Issue by MaxFerney** [ytmdesktop/ytmdesktop#1178]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

At the moment, it appears the up and down arrows on the keyboard do not link to any specific function at the moment of clicking into the window. Would it be possible to auto-focus the up/down keys to the volume slider?

My use case is swapping audio outputs often, and listening to music across all 3 platforms: speaker, headset, and vr output. How I've been handling it is selecting the volume slider (usually just clicking the slider item itself once), then using the up and down arrows to do precise volume control. what I'd like is to take out that middle step of clicking the slider itself.

### Solution

Up and down arrow *default* to volume slider precise control. If other selection that uses the up and down arrow is made, then swap to that. The default to volume slider would only be for once refocusing on the window.

example: once you select a page background or somewhere on a scrollable list, that up and down arrows now will scroll that list up and down instead of volume control.

### Alternatives

Using the shortcut mapper (just discovered crash upon using, but other report covers that enough I think) to bind it up - Current downside of shortcut mapper is it both overrides selected window - and does in increments of 10.

just continuing with how I've been doing it, since it's not too much hassle

## Suggested feature via diagram of UX flow.
![image](https://github.com/ytmdesktop/ytmdesktop/assets/46454102/06225309-b682-44aa-abcf-159ce45f37fc)

**Comment by Alipoodle** [comment]
You can set a Custom Keybind for GLOBAL Volume Control (which you have done) to something more advanced like CTRL + SHIFT + PAGE UP/DOWN
And in addition you can set the Ratio Volume to give a more scaled volume at lower levels.

Currently it won't focus on the YTM but the Window Frame.
(Hitting Tab will show this, but if you continue it will continue the focus into the window)

I feel like on it's own this is to much of a "user specific" request... rather than something which I feel can work globally...

**Comment by MaxFerney** [comment]
Agreed on the user specificness, seemed too big of a change for a niche usecase - Thank you for the advice!. The ratio volume is a wonderful solution!
