### ISSUE TITLE
<TITLE HERE>

### ISSUE THREAD

**Issue by Atomikul** [ytmdesktop/ytmdesktop#1189]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

![image](https://github.com/ytmdesktop/ytmdesktop/assets/146031110/90c0388d-4919-48c7-8dfa-48c07a91c035)

i would want minimize,maximize and close buttons

**Comment by Alipoodle** [comment]
Please can I ask for you to fill out the details required in a Bug Report (and not a Feature Request)
There's so many bits of information which we lack to understand what's going on... 😅

Am closing this so that we can have a clean slate with this all.
https://github.com/ytmdesktop/ytmdesktop/issues/new?assignees=&labels=bug&projects=&template=BUG-REPORT.yml&title=Missing%20Titlebar

**Comment by Atomikul** [comment]
I just asked for you guys to add in the next update the three buttons for minimize, maximize and close because it's annoying to close application
