### ISSUE TITLE
Change playlist cover

### ISSUE THREAD

**Issue by Temmyeiei** [ytmdesktop/ytmdesktop#1209]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Change playlist cover from your device like your pc or phone

**Comment by Alipoodle** [comment]
The AI art is the only way of changing a playlist cover which has been shared by YTM and to my knowledge this is still in early access and only a few regions have access to this.

Uploading your own one is not something I think Google are supporting, and when you get given access to the AI Cover is unknown.

If I'm wrong please do say (with some information) otherwise I will close this ticket.
