### ISSUE TITLE
If you stop playing the song and play it again, the song in your playlist will play

### ISSUE THREAD

**Issue by clcocd** [ytmdesktop/ytmdesktop#1210]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

When I stop playing the song and play it again, the song in the playlist plays. I know that this issue is reported by multiple people, but is this issue fixed in version 2? I want to know

**Comment by Alipoodle** [comment]
Could you try explaining this again?
because pausing and re-starting a song doesn't do anything like this.

if you re-select a song from the UI then it will start the song from the beginning and will play whatever "Queue" (Album, Playlist, Automix) from it.

Otherwise this sounds like a YouTube Music problem at the core and not a YTMD Problem.

**Comment by twolfson** [comment]
@clcocd I ran into this problem as well. The issue is coming from the double press logic (guessing something with the new UI broke):

https://github.com/ytmdesktop/ytmdesktop/blob/v1.14.0/main.js#L1104-L1122

My workaround is to turn off the setting mentioning "Play/Pause 2x":

<img width="895" alt="image" src="https://github.com/ytmdesktop/ytmdesktop/assets/902488/015ed616-0386-413f-8562-00289c022882">

**Comment by Alipoodle** [comment]
> @clcocd I ran into this problem as well. The issue is coming from the double press logic (guessing something with the new UI broke):
> 
> https://github.com/ytmdesktop/ytmdesktop/blob/v1.14.0/main.js#L1104-L1122
> 
> My workaround is to turn off the setting mentioning "Play/Pause 2x":
 
 Good Spot for this ❤️
