### ISSUE TITLE
Mini-Player Stuck Loading

### ISSUE THREAD

**Issue by bjgrenke** [ytmdesktop/ytmdesktop#1216]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When I switch to the mini player, I get an infinite loading animation. The playback controls don't appear. I can double click on either half of the album art to seek forward/back, but the loading circle does not go away. The only way to get back to the main player is to double click on the tray icon.

### Expected Behavior

The mini player should become functional after a brief loading animation. The loading animation should disappear and playback controls should appear when my cursor is over the mini player.

### Steps To Reproduce

1. Play a song
2. Click the mini player button in the bottom right
3. Mini player is stuck loading

### YTMDesktop

1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

### Anything else?

I have done a clean re-install and the issue persists.

**Comment by godey4me** [comment]
I have the same issue. Started happening on 12/7/23 :(

**Comment by nyoma-diamond** [comment]
This also started happening to me a couple days ago. 

I also noticed that using a hotkey to play/pause doesn't work anymore either. If a song is playing and you try to pause using a hotkey, it rapidly pauses and then unpauses again (if the song is already paused, the reverse happens when using the hotkey). If you press the hotkey multiple times in quick succession playback suddenly moves all the way back to the start of the queue/playlist that was playing (and sometimes causes the window to open or close?)

**Comment by nyoma-diamond** [comment]
Started for me as well a couple of days ago. Problem appeared simultaneously with #1214

**Comment by mingjun97** [comment]
YouTube Music has updated its media structure while our current mediaInfoProvider failed to retrieve the correct media info currently playing. We need help if someone can take a look at it.

**Comment by bjgrenke** [comment]
My mini player seems to be working again
