### ISSUE TITLE
shuffle all button in library->songs  does not work!

### ISSUE THREAD

**Issue by l911224** [ytmdesktop/ytmdesktop#1222]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

cannot press the button

### Expected Behavior

can press the button

### Steps To Reproduce

1.go to library
2.goto songs
3.shuffle all can not press

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
