### ISSUE TITLE
better documentation on API

### ISSUE THREAD

**Issue by andi242** [ytmdesktop/ytmdesktop#1277]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Update the docs.
As an API user, I would like to have a full example on the API.

Currently there is information on how to create a code, followed by how to request a token.
But how do I use this? How is the token to be put on a request (header? which header? in json?, etc.)?

I suppose the websocket is an alternative, but same issue here. 
I have no idea how to make this work.

### Solution

documentation, migration guide on how to adapt to ytm 2.0 api from 1.x

### Alternatives

make API compatible to 1.0 requests (which would be a major task)

### Anything else?

Unfortunately, I am not an developer who can dig into the code and understand how this is handled.
I want to update my integrations on streamerbot and obs to update to ytm 2.0.

**Comment by Alipoodle** [comment]
> As an API user, I would like to have a full example on the API.

This might be something we can do. @XeroxDev has put together as typescript based sdk for YTM Desktop. [XeroxDev/ytmdesktop-ts-companion](https://github.com/XeroxDev/ytmdesktop-ts-companion) with an example [XeroxDev/ytmdesktop-ts-companion (example/index.ts)](https://github.com/XeroxDev/ytmdesktop-ts-companion/blob/main/example/index.ts)

> But how do I use this? How is the token to be put on a request (header? which header? in json?, etc.)?

![image](https://github.com/ytmdesktop/ytmdesktop/assets/17199186/5f3df623-2636-45dd-8117-2bb0919e4506)

> I suppose the websocket is an alternative, but same issue here.

https://github.com/ytmdesktop/ytmdesktop/wiki/v2-%E2%80%90-Companion-Server-API-v1#socketio
You need to use the Socket.IO library for your language, with the specified URL + Partial config shown (and it says where to put the token)
and the following events from YTMD are provided in the next section

> documentation, migration guide on how to adapt to ytm 2.0 api from 1.x
> make API compatible to 1.0 requests (which would be a major task)

We likely will not be doing this, as the entire flow of the project has changed from v1 -> v2.
And we deliberately decided to NOT support the old v1 version of the application because the number of issues + Security problems which it had.
[#1139 -> New companion server](https://github.com/ytmdesktop/ytmdesktop/issues/1139#:~:text=This%20does%20mean%20that%20existing%20integrations%20with%20the%20Classic%20YTM%20Desktop%20will%20not%20function%20anymore.%20We%20considered%20making%20it%20backwards%20compatible%20but%20we%27d%20rather%20move%20forward%20with%20this%20release%20over%20the%20previous%20version%20due%20to%20a%20number%20of%20issues%20regarding%20the%20functionality%20it%20provided.)

The documentation provided has been more than enough for a few of the larger projects which have previously integrated with YTMD to be ready to go. We're happy to provide support on understanding it, but the information as shown is already in the document.

**Comment by andi242** [comment]
thank you for the fast response and the hints!
will dig through this and perhaps contribute to the wiki, if I manage to get things approriatetly done.
