### ISSUE TITLE
[Bug]: Ctrl+ALT+U causes issues and you can't start the app anymore

### ISSUE THREAD

**Issue by digihash** [ytmdesktop/ytmdesktop#1281]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I tried setting some shortcuts in the settings and when I set the shortcut Ctrl+ALT+U, the app crashed and I couldn't restart it as the same error kept popping up. I had to remove all info from AppData related to the app for it to restart again.

> YouTube Music Desktop App Crashed
> 
> Environment Details:
>     YouTube Music Desktop App 2.0.0
>     Electron 28.2.0
>     Windows NT 10.0.22631
> 
> Name: TypeError
> Message: Error processing argument at index 0, conversion failure from CmdOrCtrl+Alt+Ú
> Cause: Unknown
> 
> TypeError: Error processing argument at index 0, conversion failure from CmdOrCtrl+Alt+Ú
>     at X (C:\Users\kevin\AppData\Local\youtube_music_desktop_app\app-2.0.0\resources\app.asar\.webpack\main\index.js:8:406545)
>     at App.<anonymous> (C:\Users\kevin\AppData\Local\youtube_music_desktop_app\app-2.0.0\resources\app.asar\.webpack\main\index.js:8:429100)

### Expected Behavior

To not crash when setting that shortcut or anything with the combination of ctrl and alt basically. I tried with multiple different characters

### Steps To Reproduce

1. Go to settings
2. Go to Shortcuts
3. Set a Ctrl+Alt+some character (many different cause the issue)
4. Then it crashes

### YTMDesktop

V2.0.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
This is a similar Issue which I've had on a UK layout trying to do CTRL + ALT + A.
This is because it will do an Accented character like `ó` being replaced when using a Key like `CTRL + ALT + O` and the OS level is taking priority to convert it.

The minor issue I had with this was that the Event get's overwritten in a werid way of detecting and fixing these issues 😓 
If you go into the `%appdata%/YouTube Music Desktop App/config.json` you can edit the broken character and save it as the correct unaccented one and it will work.

**Comment by digihash** [comment]
Thanks for the fix. Maybe this can be added in the Wiki as long as it's not fixed in the code?
