### ISSUE TITLE
Bug: Settings>Shortcuts>Global/Local missing

### ISSUE THREAD

**Issue by dadi11** [ytmdesktop/ytmdesktop#206]
Hello, I've just noticed that there are some missing settings in Shortcuts tab. From strings and this comment - https://github.com/ytmdesktop/ytmdesktop/issues/106#issuecomment-594106842 I conclude that something is wrong for me and LABEL_SETTINGS_TAB_SHORTCUTS_GLOBAL/LABEL_SETTINGS_TAB_SHORTCUTS_LOCAL aren't available.
For me it looks like this: 
![image](https://user-images.githubusercontent.com/7272087/85017305-8dfce680-b16b-11ea-9909-7fc674a89bc2.png)
Thanks for bringing my polish translation so fast with 1.11 ;) 

BTW lyrics provider setting is also unavailable

**Comment by adlerluiz** [comment]
hello, thanks for contributing, the location listing I removed because it was just a preview of the keys that youtube music already uses by default, I also removed it to make room for a new implementation, custom shortcuts in the settings, and the choice of music provider now it's automatic, he tries 3 different providers, first OVH, if he doesn't find it, try it on Vagalume, and if he doesn't find it too, he'll search KSOFT
