### ISSUE TITLE
MPRIS controls missing on GNOME 3.36.4

### ISSUE THREAD

**Issue by yochananmarqos** [ytmdesktop/ytmdesktop#245]
I'm the author of the [`ytmdesktop` ](https://aur.archlinux.org/packages/ytmdesktop/)AUR package. I hadn't fired the application up in awhile and today I noticed the media controls were gone.

**Comment by rickinbsb** [comment]
can you launch the app from terminal to see if it throws any errors? I'm on elementary and they currently work for me

**Comment by yochananmarqos** [comment]
...and of course it's working now. ¯\\\_(ツ)_/¯

**Comment by rickinbsb** [comment]
hahuhahaha, If it happens again or if you get to reproduce it, please reopen this

**Comment by ricardoborgesjr** [comment]
The same problem in the GNOME 3.36.5 in Arch Linux, the terminal output:

`(node:75373) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
22:47:29.828 › error on createRightContent
22:47:43.998 › Listen: My Dude - Litany
[POST RESPONSE] : <?xml version="1.0" encoding="UTF-8"?>
<lfm status="ok">
  <nowplaying>
    <track corrected="0">My Dude</track>
    <artist corrected="0">Litany</artist>
    <album corrected="0"></album>
    <albumArtist corrected="0"></albumArtist>
    <ignoredMessage code="0"></ignoredMessage>
  </nowplaying>
</lfm>

[POST RESPONSE] : <?xml version="1.0" encoding="UTF-8"?>
<lfm status="ok">
  <scrobbles ignored="0" accepted="1">
    <scrobble>
      <track corrected="0">My Dude</track>
      <artist corrected="0">Litany</artist>
      <album corrected="0" />
      <albumArtist corrected="0"></albumArtist>
      <timestamp>1597110483</timestamp>
      <ignoredMessage code="0"></ignoredMessage>
    </scrobble>
  </scrobbles>
</lfm>`

**Comment by rickinbsb** [comment]
@ricardoborgesjr are you on 1.12.1?

**Comment by ricardoborgesjr** [comment]
Yes!
