### ISSUE TITLE
Command line / scripting / REST support

### ISSUE THREAD

**Issue by tuomas2** [ytmdesktop/ytmdesktop#386]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

I would like to command youtube music (at least play/pause) via command line and/or documented REST api. Last option might be possible already as there's remote app. Just couldn't find any API documentation.

**Comment by atcq** [comment]
There is Documentation on the Wiki. [Remote Control API](https://github.com/ytmdesktop/ytmdesktop/wiki/Remote-Control-API)

Works pretty well with `curl` from command line.
`curl --header "Content-Type: application/json" -d "{\"command\":\"track-pause\"}" http://localhost:9863/query` escaping " because of zsh.

**Comment by tuomas2** [comment]
Oh, good to know. I was trying to find this from app homepage.

**Comment by tuomas2** [comment]
I guess this can be closed then.
