### ISSUE TITLE
start minimized doesnt start minimized

### ISSUE THREAD

**Issue by artlessknave** [ytmdesktop/ytmdesktop#395]
- [y ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [y ] I verified that there is no open issue for the same subject.

**Describe the bug**
ytm is set to start minimized, but EVERY time it opens (either on startup or manually) it brings up the "What's new" thing, even when it's not new, making it no longer run in the background until I manually close it.

**To Reproduce**
open ytm.

**Expected behavior**
I expect it to start minimized like it is set to. if I want to see whats new I will click on "what's new". I don't mind as much if it's the first time but I don't need it every time the app starts. in fact, I would prefer a checkbox to never give that popup.

**Screenshots**
I can't think of useful way to get a screenshot

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.13.0***
 * OS: ***Windows*** 
 * OS version: ***10 19041.509***
 * Arch: ***x64***
* Installation way: ***exe***

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
