### ISSUE TITLE
Desktop Application starting outside of Monitors visual range.

### ISSUE THREAD

**Issue by Umaidd** [ytmdesktop/ytmdesktop#396]
- [ ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ ] I verified that there is no open issue for the same subject.

**Describe the bug**
This only started happening recently, a day ago. The app won't show up in a window, it stays in the taskbar and when I click on it, a window for the app doesn't pop up. 

**To Reproduce**
I don't see there being a particular way. I think this might have something to do with an update because it previously worked fine.
![bugreport2](https://user-images.githubusercontent.com/66977172/93642244-96ef9500-f9b2-11ea-812e-b6bbb44da4a7.png)

**Expected behavior**
I thought that when I opened the program, it'd open a window like Chrome or any other program. But this only stays in the taskbar. A visible window that I can play with isn't there.

**Screenshots**
![bugreport2](https://user-images.githubusercontent.com/66977172/93642244-96ef9500-f9b2-11ea-812e-b6bbb44da4a7.png)

**Environment (please complete the following information):**
 * YTMDesktop version: 1.13.0
 * OS: Windows 10
 * OS version: 10
 * Arch: 64x
* Installation way: .exe

**Comment by mvhancock** [comment]
I have this exact same issue.

- YTMDesktop version: 1.13.0
- OS: Windows 10
- OS version: 10
- Arch: 64x
- Installation way: .exe

**Comment by AvinashSingh786** [comment]
I had the same issue as well, uninstalled and reinstalled several times did not solve the error.

To solve the error just delete the folder C:\Users\<user>\AppData\Roaming\youtube-music-desktop-app\ and then the app basically resets and will ask you to sign in again and it works like normal after that. Just replace <user> with your account username. Ensure you close the app first then delete the folder and then open the app again.

Hope this helps.

**Comment by mvhancock** [comment]
> I had the same issue as well, uninstalled and reinstalled several times did not solve the error.
> 
> To solve the error just delete the folder C:\Users<user>\AppData\Roaming\youtube-music-desktop-app\ and then the app basically resets and will ask you to sign in again and it works like normal after that. Just replace with your account username. Ensure you close the app first then delete the folder and then open the app again.
> 
> Hope this helps.

Thank you! This solved the problem and it's working correctly again.

**Comment by gtimbo** [comment]
I'm having the same issue, but it's due to running on my laptop with another monitor connected, then restarting the laptop without the monitor connected. YTMDesktop opens assuming that the other display is still there, and so opens offscreen, with no way to move it back (the usual tricks like shift-right-click on the taskbar icon don't work on that window for some reason). I fixed it by editing `config.json` in the AppData directory mentioned above, and changing the `window-position` values back to 0,0.

**Comment by felipendc** [comment]
> I had the same issue as well, uninstalled and reinstalled several times did not solve the error.
> 
> To solve the error just delete the folder C:\Users<user>\AppData\Roaming\youtube-music-desktop-app\ and then the app basically resets and will ask you to sign in again and it works like normal after that. Just replace with your account username. Ensure you close the app first then delete the folder and then open the app again.
> 
> Hope this helps.

Oh, boy!!!! You saved my day!!!!
I'd even recorded a video showing the problem:
https://youtu.be/NNleSKOkdRM

Thanks to your tip I was able to fix the problem!

**Comment by Wrdle** [comment]
Oh wow this actually saved me @gtimbo. I dock my laptop with a thunderbolt 3 docking station to hook it up to my monitors which plays havoc with yt music desktop. Would be good if the creators were to implement a simple button on the system tray icon to reset the window position until this problem is fixed.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
