### ISSUE TITLE
Custom Album Art and Album Details

### ISSUE THREAD

**Issue by Murdock92** [ytmdesktop/ytmdesktop#492]
- [Y ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ Y] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A way to upload custom album art for albums in my library. GPMDP had this functionality, and was very nice for albums that have multiple cover variants. It would also be nice to be able to edit the details of an album in my library.

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/10045573/98469052-5a336380-21d5-11eb-8fec-789e98cabac3.png)
![image](https://user-images.githubusercontent.com/10045573/98469068-70412400-21d5-11eb-8bc9-e5b14fa2b15c.png)

**Comment by meteorsquare** [comment]
While this may be cool, the thing is: YouTube Music is coded differently from Google Play Music, so adding edit features may be borderline hacking or illegal in YouTube Music server. But I'm not exactly at expert at code and stuff (and some or all I written may be wrong) so take my word as a grain of salt.

**Comment by Murdock92** [comment]
Ah okay then, I had assumed the GPMDP did it as a local modification rather than doing something on the server. No problem if it can't be done, I'm just really missing some of my album artwork and details after the forced switch to YTM :(

**Comment by Murdock92** [comment]
My mistake, it was actually a feature of GPM itself, I thought it was just a desktop player custom feature. That is a shame then, looks like it might not be possible!

**Comment by Griffork** [comment]
When we were pushed from Google Play Music to Youtube Music we were told that all of the existing functionality would be available. This should be available on any music uploaded by the user to their own library. I just uploaded the OST from a game I bought the soundtrack for and it's showing up like this:
![image](https://user-images.githubusercontent.com/3665998/112977517-e1dc3780-91a1-11eb-98f4-428ae6038bf1.png)

Which is soo bad since I mostly navigate my library by album art :/
