### ISSUE TITLE
Songs missing metadata break a lot of things.

### ISSUE THREAD

**Issue by progranadegrinder** [ytmdesktop/ytmdesktop#515]
- [Y] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [Y] I verified that there is no open issue for the same subject.

**Describe the bug**
Upload a song with 0 metadata whatsoever, just a .mp3 with clean metadata and once you play them things like Discord Rich Presence and where it shows the songs progress in the icon on the bottom windows bar.

**To Reproduce**
1. Upload an .mp3 with no metadata.
2. Play it.
3. See error

**Expected behavior**
It'll say what song I'm playing still on Discord and still show how far the track is going.

**Screenshots**
https://gyazo.com/0a8426109c41ffceed766ed3d43fc5ed

**Environment (please complete the following information):**
 * YTMDesktop version: v1.13.0
 * OS: Windows 10
 * OS version: 2004
 * Arch: x64
* Installation way: .exe

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
