### ISSUE TITLE
Sign Out / Switch Account Doesn't Work

### ISSUE THREAD

**Issue by seifer7** [ytmdesktop/ytmdesktop#517]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
The "Sign Out" link, and "Switch Account" feature does not work.
Clicking "Sign Out" closes the menu but nothing happens.
Clicking "Switch Account" brings up my other YouTube channels but when clicking any of them nothing happens.

**To Reproduce**
1. Click your profile picture at top right
2. Click Sign Out, or click Switch Account then choose an account
3. Nothing Happens

**Expected behavior**
The YouTube/Google account should be signed out, or switched to the requested account.

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.13.0***
 * OS: ***Windows***
 * OS version: ***19042.630***
 * Arch: ***x64***
* Installation way: ***YouTube-Music-Desktop-App-Setup-1.13.0.exe***

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

This issue should be fixed as it was a problem to do with Redirecting while you were playing music :)
