### ISSUE TITLE
No Mac App for Latest Release?

### ISSUE THREAD

**Issue by alexschneider** [ytmdesktop/ytmdesktop#52]
v1.4.1 has a .pkg file, while v1.5 does not.

**Comment by mingjun97** [comment]
Currently all packages for MacOS are packaged by me. The reason why there is no .pkg file for Mac after v1.4.1 is that I upgraded my working environment to Catalina Beta and Electron Builder doesn't have support for it. I'm waiting for the community to fix this problem.
Btw, I'm currently using electron packager to build `.app` application and package `.dmg`/`.pkg` file. But it seems that it's not a good solution since the outcome size is significantly larger than electron builder's. So I didn't upload and `.pkg` or `.dmg` installation file after v1.4.1. It's welcome if you'd like to help us for packing latest version.

**Comment by mingjun97** [comment]
Since electron-builder fix this problem in 21.2.0, I can pack dmg file again. I will provide dmg and pkg file both in the future. Thanks for your loving with YTMD!
