### ISSUE TITLE
Music Cover Art Rich Presence Showcase

### ISSUE THREAD

**Issue by woosal1337** [ytmdesktop/ytmdesktop#526]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
As we know, YT Music Desktop is one of the best of its type especially, for the YT Discord Integration and Rich Presence, however, unfortunately, does not offer the cover showcase in the Discord profile instead just showing a YT Icon.[...]

**Describe the solution you'd like**
As in Spotify when we are listening to a music it also shows music's cover art. Is there any way to bring such feature to the YT Music Desktop and make it the best YT Music player ever?

**Comment by debmaj2** [comment]
Can be done with the existing LastFM Scrobbler. However, some tracks are re-uploads or Video Only Tracks (such as covers) which do not carry proper metadata.

**Comment by woosal1337** [comment]
> Can be done with the existing LastFM Scrobbler. However, some tracks are re-uploads or Video Only Tracks (such as covers) which do not carry proper metadata.

Possible, however, I doubt LastFM really supports YouTube Music.

**Comment by Plutonium-239** [comment]
I would really like this too since this truly is the best app for youtube music I have found and I have tried lots of apps. The miniplayer is just great, full of features and compact.
I don't know js or else I could've given it a shot. Might still try it since how different can it be, it's just code.
But I would love for an 'official' implementation of this

**Comment by Alipoodle** [comment]
Due to limitations within the Discord Rich Presences API, they don't allow for images to be taken from 3rd Party sources or be made on the fly.
Unlike Spotify, they have a partnership with discord allowing for them to provide the album art.

This is a feature which in the current state of Rich Presences is not possible, and unlikely to change as Discord only wishes for **Games** to use Assets uploaded to be used.

Only way this would be possible *which ultimately is completely overkill* is to have a MASSIVE collection of Discord Applications to have Album arts on but this is not easily done as each Application is limited to 250 assets, requires each album art to manually be uploaded and likely will cause issues with Discord for having so many applications setup for this.


I've already had to write a FAQ for GPMDP's wiki as a lot of people asked these questions.
> # Limitations within Discord Rich Presences
> ## Listening to Google Play Music Desktop Player
> This is not possible due to 2 reasons. We are using the Discord Rich Presences API which is only meant to be used for Games, hence the use of Playing. If we wanted to get the Listening, like Spotify, we would have to use the Discord API, which would require some form of Partnership with Discord or sketchy way of using your token (Which is against Discord TOS).
> 
> ## Playing Google Play Music Desktop Player is too long
> This has to do with the name of the Application on Discord. Sadly, we are unable to use something like Google Play Music or Play Music due to Trademark Reasons.
> 
> ## Album Art
> Due to limitations within the Discord Rich Presences API, they don't allow for images to be taken from 3rd Party sources or be made on the fly. Unlike Spotify, they have a partnership with discord allowing for them to provide the album art.
> 
> ## "Additional Features"
> Stuff like Additional features like Play on Spotify, Spectate, Ask to Join or in chat stuff are also only meant to be provided for Games/Spotify. As of recently this has been made open for game developers to have some of these features available public ally (Some require approval), but this would require some form of way that Google Play Music's can talk to each other to allow for them to play the game track / play together.

**Comment by woosal1337** [comment]
I am really sorry to hear that. Hoping Discord to add that feature for YT Music also asap!

**Comment by Alipoodle** [comment]
Discord has recently allowed for people to now use URLs for the Large Artwork allowing for us to now do this:
Track the stuff in #888 (Likely be in Development before reaching a public release for a bit)
