### ISSUE TITLE
Login with app password fails

### ISSUE THREAD

**Issue by tgr** [ytmdesktop/ytmdesktop#531]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
It is not possible to log in with [app passwords](https://support.google.com/accounts/answer/185833?hl=en). 

**To Reproduce**
1. Go to https://myaccount.google.com/apppasswords
2. Create an app password for YouTube Music Desktop App
3. Open YouTube Music Desktop App, click Sign In
4. Enter app password credentials

**Expected behavior**
I am logged into the Google account.

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Linux***
 * OS version: ***Ubuntu 20.04.1 LTS, Linux 5.4.0-54-generic x86_64***
 * Arch: ***x64***
* Installation way: ***snapcraft***

**Comment by rnett** [comment]
Seeing this with:
YTMDesktop version: v1.13.0
OS: Windows
OS version: 10
Arch: x64
Installation way: EXE

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

App Passwords are no longer used.
