### ISSUE TITLE
Select playlist on Android remote

### ISSUE THREAD

**Issue by Leomm04** [ytmdesktop/ytmdesktop#535]
- [ x ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ x ] I verified that there is no open issue for the same subject.

Hi,
It'd be cool if you could choose a playlist on your phone with the remote.
I don't think it'd be that hard to program in because you could just embed music.youtube.com in the app and if the url contains a playlist, it redirects it to the desktop.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
