### ISSUE TITLE
Allow to start paused.

### ISSUE THREAD

**Issue by Andret2344** [ytmdesktop/ytmdesktop#549]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
When I run my PC, I'd like ytmdesktop to run with it, and it works well. However, Windows system isn't good, so when someone else's run the PC and logs into another account, the last used desktop (my) is stared up after all. And then ytmdesktop, when "continue where you left off" option is on, starts to play music, and it's impossible to prevent it from doing so. There are 2 workarounds:
1. Turn off startup and leave "Continue where you left off" option turned on.
2. Leave startup turned on and turn "Continue where you left off" option off.
None of them is good, because I either need to manually run ytmdesktop or select and play the playlist from the beginning.

**Describe the solution you'd like**
The perfect solution would be to allow ytmdesktop to start where I left off, but with paused music.

**Describe alternatives you've considered**
Alternatively force startup to wait for authorization... Not sure if possible.

**Comment by adlerluiz** [comment]
Thanks for your suggestion, i will implement this functionality

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

This feature should be added in YTMD v2 now.
