### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by s4got10dev** [ytmdesktop/ytmdesktop#554]
- [ X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ X] I verified that there is no open issue for the same subject.

**Describe the bug**
On MacOS during application start error shows and application crashes. Not usable at all

**To Reproduce**
1. Configure app to continue where it finished
2. Start app
3. It crashes

**Expected behavior**
App is working

**Screenshots**
![image](https://user-images.githubusercontent.com/22197145/103405157-6fce6500-4b56-11eb-9dce-91b36ccaae0d.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Mac***
 * OS version: ***Catalina***
 * Arch: ***x64*** 
* Installation way: ***package from site or via brew***

**Comment by Alipoodle** [comment]
Fixed in #602
*Leaving open until merged into a Public released build*

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
