### ISSUE TITLE
Update electron version to latest

### ISSUE THREAD

**Issue by eatmyvenom** [ytmdesktop/ytmdesktop#559]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
Building this as a package on the AUR requires the latest version of electron to be used at the moment which is `11.1.1`

**Describe the solution you'd like**
Update this packages electron version to 11.

**Describe alternatives you've considered**
Make all of the packaged versions require electron version 10 for the time being.

**Additional context**
For the AUR packages I have marked them out of date citing the inability for the built package to be used without doing some intervention to use electron10.

**Comment by lsim** [comment]
This might fix #376

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

Updated to v28 now :)
