### ISSUE TITLE
None of the Media Keys work on macOS

### ISSUE THREAD

**Issue by eaigner** [ytmdesktop/ytmdesktop#594]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**

No single media key is recognized on macOS (Play/Pause, Prev, Next)

I checked if it could be an issue with the privacy controls, but the player has accessibility and bluetooth permissions enabled in the system preferences

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Mac***
 * OS version: ***Big Sur 11.1 (20C69)***
 * Arch: ***x86***
* Installation way: ***DMG***

**Comment by mingjun97** [comment]
Could you kindly try the pre-release version for v1.14.0? v1.13.0 has this problem due to the malfunction of Electron.

**Comment by eaigner** [comment]
Yes, seems to work in 1.14

**Comment by autoferrit** [comment]
I just installed the v14 pre-release. And I am still not able to use my media keys on my keyboard. As suggested in other issues, all my browsers have the media key flag turned off.

One thing I know I did is disable my computer from launching iTunes whenever I hit play since I don't use itunes. Though I don't remember how I did that.
![image](https://user-images.githubusercontent.com/89895/150653928-7772f59b-aef3-4a86-a30e-37be2eaf11be.png)

**Comment by DanDobrick** [comment]
I'm also having this issue. I fixed it on an older computer of mine, but after installing it on this new one the issue came back.

**Comment by JonUleis** [comment]
I fixed this by installing the pre-release DMG and following these steps: https://github.com/ytmdesktop/ytmdesktop/issues/304#issuecomment-767852922

However, and this may be a separate issue, trying to play/pause my music with a Bluetooth headset (Pixel Buds Pro) still opens the macOS Music app instead of pausing like the media keys.

**Comment by bitkris-dev** [comment]
Guys, I've found an easy solution to the problem using Karabiner. This is the complex modification I've created to map the standard media keys to YTMDesktop default shortcuts and it works like a charm :)

`{
  "title": "Media Keys Remapping for YTMDesktop App",
  "rules": [
      {
          "description": "Media Play/Pause => Cmd+Shift+Spacebar",
          "manipulators": [
              {
                  "from": {
                      "key_code": "play_or_pause"
                  },
                  "to": [
                      {
                        "key_code": "spacebar",
                        "modifiers": [ "left_command", "left_shift" ]
                      }
                  ],
                  "type": "basic"
              }
          ]
      },
      {
          "description": "Media Next Track => Cmd+Shift+PageUp",
          "manipulators": [
              {
                  "from": {
                      "consumer_key_code": "scan_next_track"
                  },
                  "to": [
                      {
                        "key_code": "page_up",
                        "modifiers": [ "left_command", "left_shift" ]
                      }
                  ],
                  "type": "basic"
              }
          ]
      },
      {
          "description": "Media Prev Track => Cmd+Shift+PageUp",
          "manipulators": [
              {
                  "from": {
                      "consumer_key_code": "scan_previous_track"
                  },
                  "to": [
                      {
                        "key_code": "page_down",
                        "modifiers": [ "left_command", "left_shift" ]
                      }
                  ],
                  "type": "basic"
              }
          ]
      }
  ]
}`
