### ISSUE TITLE
AppImage Memory Leak

### ISSUE THREAD

**Issue by kwehmeyer** [ytmdesktop/ytmdesktop#603]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**AppImage Memory Leak**
Running the app image with `--no-sandbox` results in a memory leak.

**To Reproduce**
1. Download AppImage
2. `$ chmod a+x *.AppImage`
3. `./*.AppImage --no-sandbox`

**Expected behavior**
Terminal output is as such:
```
Checking for update
(node:7254) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Update for version 1.13.0 is not available (latest version: 1.13.0, downgrade is disallowed).
(node:7254) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
```

Followed by the slow death and eventual shutdown of the computer.

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.13.0***
 * OS: ***Debian 10 Buster***
 * OS version: ***4.19.0-13-amd64 ***
 * Arch: ***x86***
* Installation way: ***AppImage***

**Comment by Walkman100** [comment]
@kwehmeyer does this happen to you without `--no-sandbox`? My computer crashed last night because of YTMDesktop (Win10, YTMD v1.13), windows event logs says `Resource-Exhaustion-Detector: YouTube Music Desktop App.exe (17412) consumed 20654759936 bytes`
My total virtual memory size is 32GB, YTMD should not be using 20GB...

**Comment by kwehmeyer** [comment]
@Walkman100 It happens both with and without sandbox. `sudo` and user access. Whether the app is extract and run from the extracted dir or not. I think I've pretty much tried everything in terms  of running the appimage. Lot's of other appimages face similar issues and I believe it's an issue with electron and  `--no-sandbox` is a workaround. However, that doesn't explain the performance issue's you noticed. 

Additionally, I have been able to start the AppImage like once or twice on Debian by using the `--no-sandbox` flag but inevitably it just crashed xserver and I had to restart my computer (memory leak?).

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
