### ISSUE TITLE
Active link to https://ytmdesktop.app in About

### ISSUE THREAD

**Issue by kudlav** [ytmdesktop/ytmdesktop#605]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
In About app section of settings there is link to https://ytmdesktop.app. But this link is not clickable and cannot be even copied.
There is no way how to visit github or webpage from the app.

**Describe the solution you'd like**
Make the About link active, clickable.

**Additional context**
v1.14.0

![obrazek](https://user-images.githubusercontent.com/11516259/106570504-42e6e680-6536-11eb-8ed5-e6ce0158e0dc.png)

**Comment by mingjun97** [comment]
Thanks for advising!

A patch has been pushed to development branch.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
