### ISSUE TITLE
Release deb package

### ISSUE THREAD

**Issue by JoeJoeTV** [ytmdesktop/ytmdesktop#625]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.(Searched for deb and ppa in the issues section and I couldn't find any downloads for deb packages)

**Describe the solution you'd like**
I would like there to be releases as deb packages, because I find them easier to manage and smaller aswell as more compatible than flatpaks.

**Describe alternatives you've considered**
I am currently using the AppImage variant, but it's just kinda sitting in my Downloads folder.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

New release has a deb and rpm version of the app <3
