### ISSUE TITLE
Mac OS: media keys not working

### ISSUE THREAD

**Issue by DennisBecker** [ytmdesktop/ytmdesktop#64]
I am running the app on a Mac Book Pro but I cannot use the global Mac shortcuts for play/pause or next / previous song. I have configured the keys so that I have to combine them with FN + F7, F8 or F9. The gobal shortcut CMD + SHIFT + SPACE works. The bad thing is, I don't have page up or page down keys ...

**Comment by mingjun97** [comment]
Thanks for your feedback!
There might be several reason for it. Could you try the following steps to see if it works?
1. If you upgrade to MacOS Catalina, this might caused by the permission controls. Navigate to `System Preference` -> `Security & Privacy` -> `Privacy` -> `Accessibility`, you will see `YTMDesktop` shown in the list. Mark the check corresponding with it(If it has already been checked, try uncheck and then check it). After doing that, make YTMDesktop full exit (either via `Cmd+Q` or select `quit` in the dock) then restart it.
2. If previous doesn't work or you are running in the older MacOS, you may try to navigate `chrome://flags/#hardware-media-key-handling` and set it to be `Disabled` using Google Chrome then restart your system or try to relaunch both Google Chrome and YTMDesktop.

**Comment by DennisBecker** [comment]
This works with version 1.5.2
