### ISSUE TITLE
Mac OS: Accessing settings from Mac OS task bar results in empty settings windows

### ISSUE THREAD

**Issue by DennisBecker** [ytmdesktop/ytmdesktop#65]
In Mac OS you have a small app icon on the top right where are some menu entries like next or previous song, thumbs up/down and settings. When I click on settings, the app comes to the foreground and opens the settings overlay window but shows nothing and I am unable to close this window. I have to quit the app completely to get rid of it.

**Comment by mingjun97** [comment]
Thanks for feed back. I'll inspect on it recently.

**Comment by mingjun97** [comment]
Did you mean `the top right` as the tray icon where you have sorts of battery and clock indicators? I believe it might be the crappy code regard the provider refactoring I wrote in previous releases. It might get fixed in the latest release. (as far as I tested, everything works good) Could you try it out?

Thanks

**Comment by DennisBecker** [comment]
fixed in 1.5.2
