### ISSUE TITLE
YTMDesktop logs too much to the syslog

### ISSUE THREAD

**Issue by alexgmin** [ytmdesktop/ytmdesktop#654]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
I think ytmdesktop logs too much to the log. I don't know if this affects SOs other than linux.

**Describe the solution you'd like**
Change the logging the application does to be on debug instead of info. 
This one is specially egregious, logging every song is listened to /var/log/syslog
https://github.com/ytmdesktop/ytmdesktop/blob/27e745237034a59491935df75873a9d10196c6aa/main.js#L561

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
