### ISSUE TITLE
"New recommendations" Ends Queue, Repeatedly

### ISSUE THREAD

**Issue by RevanMalak009** [ytmdesktop/ytmdesktop#657]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
The "new recommendations" task is ending my session. Also, that task keeps repeating. My playlist/radio session gets lost, sometimes a few times within a minute or after only 1 song. Usually happens upon song end. I have to, again, find it; and, then, hear songs repeat. Also happens when playing a single song.

**To Reproduce**
3. See error

**Expected behavior**
Current queue should be unaffected by new recommendation.

**Screenshots**

**Environment (please complete the following information):**
 * YTMDesktop version: v1.13.0
 * OS: Windows
 * OS version: Current Windows 10 Pro //Sorry. I'm running Cairo Shell, so can't check version.
 * Arch: x64
* Installation way: .exe because I can't run apps on Cairo Shell.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
