### ISSUE TITLE
Sound settings on Windows 10 are not recognized

### ISSUE THREAD

**Issue by kaijen** [ytmdesktop/ytmdesktop#669]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
I have changed the Sound settings for YTMDesktop in Windows 10 to route the sound to a different device than the standard output device. YTMDesktop does not recognize this setting most of the time although I tried to restart. I got it working a frew times but could not detect which factors where responsible for getting the setting to work.
I need YMTD to correctly honor sound settings to route music with Voicemeter VB Potato.

**To Reproduce**
1. Route sound to a different device than the default in Windows sound settings
2. Play music with YTMD

**Expected behavior**
Music should be routed to the device selected in the Windows sound settings.

**Screenshots**
n/a

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.9.0***
 * OS: ***Windows***
 * OS version: ***10***
 * Arch: ***x64***
* Installation way: ***Default for Windows***

**Comment by Alipoodle** [comment]
Can I confirm that you are using Version **1.9.0**?

There have been a few audio changes to the Audio Selection since then including Ability to Select audio from Tray Icon + A Selector within the settings.
(please ignore the labelling on the left)
![image](https://user-images.githubusercontent.com/17199186/111991267-071ad700-8b0c-11eb-9fd7-a1ab502b4b13.png)

**Comment by kaijen** [comment]
Sorry, my fault - I did not check a new version. The problem related to 1.9.0 which I really was using. 1.13.0 fixed the problem for me!
Thank you very much for the great app!
