### ISSUE TITLE
Couldn't sign in

### ISSUE THREAD

**Issue by diegocade1** [ytmdesktop/ytmdesktop#67]
Hi, is there a work around about this 'You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.' message?, finally find the app I was looking for but I got stuck here
![image](https://user-images.githubusercontent.com/46531987/69763705-d364b280-114c-11ea-96c1-f4f5c45694bf.png)

**Comment by mingjun97** [comment]
Which system are you using?

**Comment by diegocade1** [comment]
> 
> 
> Which system are you using?

windows 10 64bit

**Comment by diegocade1** [comment]
I have 2FA in my account, is that a problem?

**Comment by mingjun97** [comment]
I have 2FA in my account too. It seems I don't have such problem. Do you have chrome installed in your system?

**Comment by diegocade1** [comment]
> I have 2FA in my account too. It seems I don't have such problem. Do you have chrome installed in your system?

Yeah

**Comment by adlerluiz** [comment]
@diegocade1 Have you the latest release?

https://github.com/ytmdesktop/ytmdesktop/releases

**Comment by diegocade1** [comment]
I checked the version and its the latest, sadly I still have the issue

**Comment by mingjun97** [comment]
Sorry, we can't reproduce your issue in our environment now. So that we can't fix it at this moment.
Maybe you can try the following suggestions:
1. Clean up cookies of YTMDesktop.
2. Check your internet connections to see whether you have proxy or DNS misconfiguration.
3. Try to login with another account to see if it occurs again.

Again, thanks for your feedback and love our application!

**Comment by AdityaTD** [comment]
I could replicate this issue on Windows 10 64bit as well. https://i.imgur.com/wXuR5VI.png
Using v1.5.3 of this app, I also have 2FA on.

Just an idea, what if you used an external popup to log in so you could log in via Chrome or any other browser and it'd call back to the app with the login tokens which could be injected in the electron browser thus not having to face this issue at all?

**Comment by diegocade1** [comment]
> 
> 
> Sorry, we can't reproduce your issue in our environment now. So that we can't fix it at this moment.
> Maybe you can try the following suggestions:
> 
>     1. Clean up cookies of YTMDesktop.
> 
>     2. Check your internet connections to see whether you have proxy or DNS misconfiguration.
> 
>     3. Try to login with another account to see if it occurs again.
> 
> 
> Again, thanks for your feedback and love our application!
I tried everything, still no luck

**Comment by AdityaTD** [comment]
Unfortunately, the issue is much greater affecting all Chromium-based applications along with Electron which depends on Chromium that authenticate with Google services.

**Read More Here:** https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html

**Current Fix:** Set this as the user agent for the `mainWindow` or `view` in your case and it should technically work `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0`

**Comment by diegocade1** [comment]
Thank you all who take their time to read this issue and started making a solution, finally I can use it as intended. Thank you very much.

**Comment by adlerluiz** [comment]
thank you for using and letting us know about problems that happen

**Comment by aohontsev** [comment]
> Thank you all who take their time to read this issue and started making a solution, finally I can use it as intended. Thank you very much.

JFYI: I have the same issue then have running Fiddler proxy (with decoding HTTPS). Disabling its help me with problem. So just try to disable any proxies in system. Hope its help.
