### ISSUE TITLE
Setting to only scan the Clipboard for music.youtube.com Link

### ISSUE THREAD

**Issue by TimTrayler** [ytmdesktop/ytmdesktop#678]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
Not really, it's just annoying.

**Describe the solution you'd like**
Hey, wouldn't it be a great setting to have the Clipboard only be scanned for music.youtube.com links instead of all YouTube links because the popups when I copy YouTube Links really annoy me.

**Describe alternatives you've considered**
An alternative would be to have a setting, which toggles between all YouTube Links and YouTube Music Links.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
