### ISSUE TITLE
 Buttons overlapping in top bar on windows with narrow width

### ISSUE THREAD

**Issue by MaxMatti** [ytmdesktop/ytmdesktop#703]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
Buttons overlapping in top bar on windows with narrow width

**To Reproduce**
1. Make window small

**Screenshots**
<img width="268" alt="image" src="https://user-images.githubusercontent.com/1584478/115546563-79b2da00-a2a5-11eb-8551-08b28ede995b.png">

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Linux***
 * OS version: ***Archlinux*** (rolling release)
 * Arch: ***x64***
* Installation way: ***AUR***

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
