### ISSUE TITLE
Last.FM integration doesn't connect

### ISSUE THREAD

**Issue by UstedLoco** [ytmdesktop/ytmdesktop#710]
- [x ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ x] I verified that there is no open issue for the same subject.

**Describe the bug**
After inputting last.fm username and password, and granting access, scrobbling doesn't happen and app doesn't appear in the list of connected apps on last.fm.

**To Reproduce**
1. Settings, Integrations, last.fm
2. Put in username/password
3. Grant access in last.fm pop up, receive confirmation
4. YTMDesktop does not scrobble, does not appear in list of applications on last.fm

**Expected behavior**
Scrobbling, and app appearing in the list of connected apps on last.fm.

**Screenshots**

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.13.0***
 * OS: ***Windows*** 
 * OS version: ***10***
 * Arch: ***x64***
* Installation way: ***.exe 
![Capture](https://user-images.githubusercontent.com/83165401/115991176-5e8de600-a595-11eb-957c-2a21131cf400.JPG)
![Capture1](https://user-images.githubusercontent.com/83165401/115991177-5f267c80-a595-11eb-9796-99d8b978896f.JPG)
![Capture2](https://user-images.githubusercontent.com/83165401/115991178-5f267c80-a595-11eb-86bf-c919a602caa3.JPG)
![Capture3](https://user-images.githubusercontent.com/83165401/115991179-5f267c80-a595-11eb-9f4f-f1ac02d11e07.JPG)

***

**Comment by Alipoodle** [comment]
![image](https://user-images.githubusercontent.com/17199186/115991312-b8a3a100-a5bf-11eb-959e-bec7548c1527.png)

I was having issues with it initially getting it to show with in the auth list. However after a few minutes & a full restart of YouTube Music Desktop App, it had successfully shown within the list and is Scrobbling successfully.

It may be an issue that Upon getting authorisation we don't actually use the Authorisation and because of that it fails to work until the app is restarted. 🤔

**Comment by UstedLoco** [comment]
Restarted the app a few times, no luck.

**Comment by NeonLightning** [comment]
same here. tried reloading a few times. tried signing in a few times. and still not showing up.

**Comment by xEntrance** [comment]
Same here. Still not working

**Comment by d0x7** [comment]
I also have the same issue. Just found about this project, looked great, tried out some features and I was really happy about it.. then I noticed the scrobbling doesn't work at all.. 

Also, why do I have to enter my credentials in the app itself, when I'll be redirected to Last.FM' OAuth Page anyways? It says `You have granted permission to ytmdesktop to use your Last.fm account.`, but it neither scrobbles the tracks, nor does the application actually show up on my Last.FM account. I've restarted the app multiple times, deleted the credentials, didn't enter them on the app at all (only via oauth), clicked the switch first, then the cog to set it up... nothing worked for me, unfortunately.

I would've tried to debug it myself, but it seems that any way of opening the dev tools (to see a potential error) is disabled (F12, CTRL+ALT+I, CTRL+SHIFT+I, etc.).

Could the issue eventually be about that the authorization is granted successfully, but the token not (correctly) returned to the app itself, hence not showing up in the application list, because the token is never used? 

I would be really glad if you make this issue a higher priority, because this seems to happen for 1,5 months now, there is no update about this and the feature would been mostly the reason to use this app for me (otherwise I can go back to use edge w/ scrobbler extension).

Anyways, thanks for the great work on the app otherwise! :)

**Comment by d0x7** [comment]
I also have the same issue. Just found about this project, looked great, tried out some features and I was really happy about it.. then I noticed the scrobbling doesn't work at all.. 

Also, why do I have to enter my credentials in the app itself, when I'll be redirected to Last.FM' OAuth Page anyways? It says `You have granted permission to ytmdesktop to use your Last.fm account.`, but it neither scrobbles the tracks, nor does the application actually show up on my Last.FM account. I've restarted the app multiple times, deleted the credentials, didn't enter them on the app at all (only via oauth), clicked the switch first, then the cog to set it up... nothing worked for me, unfortunately.

I would've tried to debug it myself, but it seems that any way of opening the dev tools (to see a potential error) is disabled (F12, CTRL+ALT+I, CTRL+SHIFT+I, etc.).

Could the issue eventually be about that the authorization is granted successfully, but the token not (correctly) returned to the app itself, hence not showing up in the application list, because the token is never used? (as seen on the screenshot)

I would be really glad if you make this issue a higher priority, because this seems to happen for 1,5 months now, there is no update about this and the feature would been mostly the reason to use this app for me (otherwise I can go back to use edge w/ scrobbler extension).

Anyways, thanks for the great work on the app otherwise! :) 

![image](https://user-images.githubusercontent.com/17951467/120923711-3d5e0080-c6d0-11eb-8662-56cd30d955de.png)

**Comment by iamhenry** [comment]
I am also running in to this issue. I've connected successfully on a Mac but the lastfm site doesn't show the scrobbles.

**Comment by Alveel** [comment]
I am experiencing the same issue. It worked before, but I had to sign in again after changing my username, after which scrobbling stopped working (in hindsight maybe signing in again was not a requirement, but alas.)

Same version and platform as OP, except I used scoop to install it. Its configuration is still in appdata.

**Comment by jonchapple** [comment]
Same issue here. Recently switched from a Mac to Windows laptop and while it worked with the former, it won't connect with the Windows app.

I go through the linking/sign-in process and it says it's logged in on the player end, but it doesn't show in the connected apps on Last.fm and doesn't scrobble songs.

**Comment by ChopsII** [comment]
+1, "me too"

**Comment by Justin092** [comment]
Same here, I stopped using YTMD for a few months because I like to utilize the integration with Last.FM and Botisimo to tell chat what songs are playing. Unfortunately, due to this issue, that seems to be impossible at this time. I don't want to switch away as I find it annoying to have to have YouTube Music AND Spotify and this app is exactly what I need. So, hopefully this can get fixed.

**Comment by renatolond** [comment]
Couldn't find a way around this, the app seems to print an error if I open it throught terminal, but not enough info to see where it's coming from
```
[INVALID RETURN] the return was invalid JSON: TypeError: Cannot read property 'key' of undefined
```

**Comment by Alveel** [comment]
I'm not sure what I did (if anything), but it started working again! I didn't have to do anything, it just works now for some reason. Perhaps it was something on YT's end, or does it still not work for most of you?

**Comment by Mertica** [comment]
Hmm, I've just installed and set everything up, and Discord Rich Presence took a restart to actually properly integrate and show up, but last.fm is still not showing up at all, including in the Applications tab, even after restarts

**Comment by whiplash159** [comment]
I've got the same problem with Last.fm. It does not work for at least 3 weeks now. It does not work for me in 1.13.0 and also the same problem appears in 1.14.0 (which I installed to test it out).

**Comment by JOM13** [comment]
Same here. I did have ytmdesktop on the Last.fm authorised application list but it's not scrobbling since 7 December 2021. I removed it and tried to reconnect with no luck. Hope it works again soon.

**Comment by pratyakshm** [comment]
Same, does not work here either on Windows 11 22621 (22H2).

**Comment by gauthierguillaume** [comment]
I have the exact same issue since months, I don't know why either...

**Comment by WOOOOO0** [comment]
I'm having the same issue here, is this just something with no known solution still?

**Comment by chriskol** [comment]
As common to above, it looks like it last worked Dec 2021.  I just downloaded the latest pre-release 1.14.2 and still no dice on it working

**Comment by FASouzaIT** [comment]
I was having the same issue, here's what I did:
On Last.fm I logged out from everywhere (you can find it here: https://www.last.fm/settings/account) and then configured YouTube Music Desktop App.

After that, I restarted the app and played a song. When I started playing it also started scrobbling and added YTMDesktop to connected applications on Last.fm too.

**Comment by gauthierguillaume** [comment]
> I was having the same issue, here's what I did: On Last.fm I logged out from everywhere (you can find it here: https://www.last.fm/settings/account) and then configured YouTube Music Desktop App.
> 
> After that, I restarted the app and played a song. When I started playing it also started scrobbling and added YTMDesktop to connected applications on Last.fm too.

Definitely works, restarting the app after resetting everything work like a charm, thanks mate

**Comment by chriskol** [comment]
> I was having the same issue, here's what I did: On Last.fm I logged out from everywhere (you can find it here: https://www.last.fm/settings/account) and then configured YouTube Music Desktop App.
> 
> After that, I restarted the app and played a song. When I started playing it also started scrobbling and added YTMDesktop to connected applications on Last.fm too.

I tried this and it didn't work.

So I tried this again but disconnected all my apps as well first.  When I authorized Last.Fm through YTMDesktop though everything seemed to be fine and it said it was added.  But when I go to the 'Applications' page, ytm desktop is no longer there...
