### ISSUE TITLE
YTM change audio output device

### ISSUE THREAD

**Issue by tisukk** [ytmdesktop/ytmdesktop#714]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
I use Voicemeeter and YTMD change audio output device. but in the settings don't change, to resolve the issue I have to manually go to the setting tabs and change the audio output device to the good one. sometimes it happend at every song but sometimes I can listen to music an entire day without the audio output device change.

**To Reproduce**
Listen to music

**Environment**
YTMDesktop version: v1.13.0
OS version: 10.0.19042.928
Arch: x64
Installation way: .exe

**Comment by ollimaz** [comment]
Same happens to me! 
I think this only happens if the audio output is different from the normal windows output device.

**Comment by totorus** [comment]
Hello
Exactly the same thing for me.

I use Voicemeeter Potato with a virtual cable from them to direct all music software to a separate channel.
This allows me to control the sound independently from the rest of the audio on my PC.

From time to time the software switches to the default Windows sound output (which is also a Voicemeeter input of course) although the setting has not changed in YTDM.

I have to select another output and then switch back to my cable output to get it to work again.

**Comment by londospark** [comment]
Apologies for the necro but this is happening to me too.

**Comment by WestonHawk** [comment]
Same issue here. Voicemeeter Potato with my default Windows audio device set to Voicemeeter Input and YT music set to Voicemeeter AUX Input. 

This isn't actually a Voicemeeter specific issue, it is just most apparent to Voicemeeter users because of how it utilizes separate virtual audio devices. I can replicate this issue with my default audio device set to my rear motherboard 3.5mm output and YTMDP set to my microphone's 3.5mm output.

I can most easily replicate the issue by pressing the previous song (skip back) button just as a song is about to end (0:02 seconds remaining) and before it starts playing the next song in queue. The settings in YTMDP still have the non-default audio device set as the output but audio has clearly switched to the default Windows audio device.

You HAVE to have another song in queue to replicate this. It doesn't work if autoplay is off and you are at the end of an album/single. This leads me to believe the issue stems from buffering the next song.

For everyone running into this issue, you can quickly switch it back the correct audio device by clicking an empty spot on the bottom player bar (or click the arrow in the bottom right) to bring up the "Up Next" queue screen. This for some reason fixes it right away and is much quicker than opening settings.

Still, it is more than enough time to blow my eardrums out since I use Voicemeeter for volume leveling and EQ.

**Comment by tvandinther** [comment]
Appears to be the same issue as #520

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
