### ISSUE TITLE
YTMdesktop crashes my windows pc completely

### ISSUE THREAD

**Issue by george-kant** [ytmdesktop/ytmdesktop#718]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
I can not understand exactly what is happening. My PC crashes completely if I listen to music for about 1 hour or more. The computer is becoming more and more laggish and in the end I have to reset it. When I check the memory consumption from the app is high but not high enough to explain this problem.

Important Note: This only happens with YTMD. I am now using the YouTube Music Chrome extension app and have had no problems for days.

**To Reproduce**
Using the app for about 1 hour or more

**Expected behavior**
No crashes

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.13.0***
 * OS: ***Windows***
 * OS version: ***10***
 * Arch: ***x64***

**Comment by alex534488** [comment]
same problem, this app is taking 500mb of my memory and I encountered a crash with my pc recently. Ill try to disable hardware acceleration and I'll see how it goes

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
