### ISSUE TITLE
Discord Rich Presence does not work with some songs.

### ISSUE THREAD

**Issue by hellojo011** [ytmdesktop/ytmdesktop#719]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
Discord Rich Presence does not work when playing certain songs.
If change to this song while listening to another song, the information of that song does not change.

**To Reproduce**
1. Search 'way back home - Shaun' (This is one of the songs that have a problem.)
2. Playing Music
3. Check out my profile on Discord.
or
1. Play any song.
2. Search 'way back home - Shaun'
3. Playing Music
4. Check out my profile on Discord.

**Expected behavior**
Discord's My Profile shows exactly the songs you're listening to.

**Screenshots**
![image](https://user-images.githubusercontent.com/15025232/116946789-09995080-acb6-11eb-89f5-024e5cca591f.png)
![image](https://user-images.githubusercontent.com/15025232/116946907-59781780-acb6-11eb-8221-2fa4c73be569.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.14.0***
 * OS: ***Windows***
 * OS version: ***Windows 10 Version 20H2***
 * Arch: ***x64***
* Installation way: ***installing .exe file ***

**Comment by LastPlayerTR** [comment]
YTMDesktop version: 1.13.0
OS: Windows
OS version: Windows 10 Version 20H2
Arch: x64
Installation way: ***Builded***
Not happening on my client. 
Can it be about Rate Limit or connection error?

**Comment by hellojo011** [comment]
probably not. other any song is playing, Discord Rich Presence is working. but specific songs is not.

Do I need to reinstall the client?

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

This bug was to do with Single Character Artists/Albums or Song names as Discord requires 2 characters minimum.
This issues is fixed in YTMD v2
