### ISSUE TITLE
"Continue where you left off" does not work

### ISSUE THREAD

**Issue by pdario** [ytmdesktop/ytmdesktop#740]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
"Continue where you left off" used to work on my old PC; now I changed it and installed YTMD back, but now the "continue where you left off" feature does not work: I loose the playlist I was listening to and I have to manually start a new one.
I tried cycling the toggle off and then on again.

**To Reproduce**
1. Start a Playlist or shuffle
2. Close YTMD
3. Restart YTMD
4. Nothing plays

**Expected behavior**
"Continue where you left off"

**Screenshots**
N/A

**Environment (please complete the following information):**
 * YTMDesktop version: 1.13.0
 * OS: Windows
 * OS version: 10 21H1
 * Arch: x64
* Installation way: installation package

**Comment by KegNot** [comment]
Same here on W10 20H2.
I'm new to YTMD so I can't tell about previous behavior.
Did all the things pdario did with no effect.

Before discovering this github I sent an e-mail to Adler. Hope someone will respond.

**Comment by KegNot** [comment]
I found pre-release v1.14.0 and tried that. Nope. "Continue where you left off" doesn't work with that version either.

**Comment by KegNot** [comment]
Got a reply from Adler Luiz. It has to with the play bar. Whether it has focus at the moment the app is shut down. His literal reaction: "Well it's a 'little problem' in the way youtube music works, there's only way to know which playlist or song you're currently on, if you have the bar open, so the 'resume where you left off' mode will work."

This "state" will not remember because the bar is "closed":
![image](https://user-images.githubusercontent.com/59098871/122671580-add44980-d1c7-11eb-9f50-2e1093efbd62.png)

This "state" will remember because the bar is "open":
![image](https://user-images.githubusercontent.com/59098871/122671645-fdb31080-d1c7-11eb-8459-5d2a6c6408f4.png)

Click the triangle at the bottom right (or any "empty" part of the bar) to open or close the bar.

**Comment by mingjun97** [comment]
The way YTMD dealing with `continue where you left off` is to record the URL you currently viewing. With bar on, you can get URL like this.
![image](https://user-images.githubusercontent.com/15214491/123014551-5bd42500-d37b-11eb-935c-3321313635e8.png)

With bar off, your URL will be like this.
![image](https://user-images.githubusercontent.com/15214491/123014585-68f11400-d37b-11eb-9ec1-b2b8dd9c01ac.png)

I prefer to leave this issue open. I believe there must be a more generic way to get the id of current song and playlist instead of observing the URL and we should switch to it. Thanks for pointing this out!

**Comment by adlerluiz** [comment]
we're going to check and improve the way the app handles this

**Comment by adlerluiz** [comment]
Now on wiki - https://github.com/ytmdesktop/ytmdesktop/wiki/Know-issues

**Comment by NovusTheory** [comment]
Fixed in the PR above
