### ISSUE TITLE
Cannot see main interface on Windows 

### ISSUE THREAD

**Issue by brianbotkiller** [ytmdesktop/ytmdesktop#766]
- [ y] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ y] I verified that there is no open issue for the same subject.

**Describe the bug**
I am running the latest build on my system, Win 10 pro. I cannot see the interface at all. If I open the app and mouse over the icon in the taskbar, I can "see" the interface in the preview window, but  I cannot open the interface. 

I can open the miniplayer, but if I hit the expand button to show the full interface, it goes away and I do not see the full interface. 

I have un/reinstalled. 

**Screenshots**

**Environment (please complete the following information):**
 * YTMDesktop version: ***latest***
 * OS: Win 10 pro
 * OS version: 20H1
 * Arch: ***x64***
 * Installation way: .exe from site 

![Untitled](https://user-images.githubusercontent.com/41643/125130176-cac0b600-e0bd-11eb-9291-6b3122593ddc.png)

**Comment by brianbotkiller** [comment]
NVM, sorry, rebuilt, cleared appdata and good to go.

**Comment by Alipoodle** [comment]
This issue is likely to do with the position of it going off.

If this happens again you can try:

This issue has occurred for a few people.

# How to fix
Please do the following:
- Open the following folder: `%appdata%/youtube-music-desktop-app` (you can use File Explorer or Run to open this)
- Open the `config.json` file.
- Navigate to the area where it says
```json
"window-position": {
```
 
- Replace the following fields displayed below:
 ```json
	"window-position": {
		"x": 230,
		"y": 40
	},
	"window-maximized": false,
	"window-size": {
		"width": 1340,
		"height": 970
	},
```
This will set the Window to be around the middle of the screen for you.

## Video for setting
_I used some other numbers in this but used what I put above_
![2021-07-03_18-58-43](https://user-images.githubusercontent.com/17199186/124363028-bb121f00-dc30-11eb-85b9-50e1c4780fa0.gif)

For some reason some people's `"window-position"` seems to be going -32,000, and going WAYYYYY to far of the screen.
