### ISSUE TITLE
[SECURITY] The way that last.fm credentials are stored NEEDS to be changed

### ISSUE THREAD

**Issue by xhoneybear** [ytmdesktop/ytmdesktop#796]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
There is a HUGE security problem related to how the last.fm password is stored. Anyone who has access to a person's computer may know the password if they only know what they are doing. Storing last.fm password in config file while it's only base64-encrypted is highly insecure. You only need to paste it into a random web base64 decryptor and you have a password just like if it was in plain text. It needs to be patched ASAP.

**Describe the solution you'd like**
I would strongly advise using a keyring or a stronger encryption method like AES 256 or using a keyring

**Describe alternatives you've considered**
None really. There is little room to work here, the password needs a better way of storing it

**Additional context**
I stumbled upon that when I was going to change window resolution of the app. I saw a familiar encryption scheme, decided to see if it's what I thought it was, pasted the "password" string into an online base64 decryptor and output showed me my last.fm password... It's not safe. It's not much more secure than plain text

**Comment by Alipoodle** [comment]
This has been discussed internally about using Windows Credential Manager /Mac's Keychain, however due to lack of progress on much development, it's been left a bit at the moment.

It will probably be done eventually for increased security for the application.
Although I feel that a full Revamp of the Authentication system with L.FM is probably needed with some people having issues with squabbling in the first place.
