### ISSUE TITLE
Always show volume slider

### ISSUE THREAD

**Issue by DorCoMaNdO** [ytmdesktop/ytmdesktop#838]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
The volume slider disappears when the cursor isn't over it's area, which then leads to more time spent waiting for it to reappear for volume adjustments with the scroll to work (sometimes needing the cursor to be moved away and back since scroll capturing does not always work), one of the bigger issues I've had with YTM since GPM's deprecation.

**Describe the solution you'd like**
A toggle to stop the volume slider from fading away on focus loss, and for scroll capture to be always/more responsive when the cursor is over the slider (though it already feels somewhat more responsive than it does in the browser).

**Describe alternatives you've considered**
In the browser I've tried a few different uBlock rules, while I could keep it visible, scripts still prevented scrolling from functioning most of the time unless I put the cursor over it, away from it, and over it again.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

This feature has been added in YTMDv2 :)
