### ISSUE TITLE
allow to play a song sending a link to the api

### ISSUE THREAD

**Issue by akabakass** [ytmdesktop/ytmdesktop#853]
- [ x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
nope, not really
I was browsing youtube, found a nice sound, wanted to listen to it on the app but had to search for it in the app (just a copy paste away really).
So I was wondering if it would be possible to make maybe an extension to add some kind of button on youtube page via an extension  to send a youtube link to the app via the api  that i can build
after looking at the api, unfortunately, there not seem to be a way to add a song via a link.
I've found the clipboard read thing, but it's still a two step process, so not exactly perfect to me

**Describe the solution you'd like**
allow to play a song in the app passing a link via the api

**Describe alternatives you've considered**
just copy/paste the title of the vidéo :)

**Additional context**
nope

**Comment by flleeppyy** [comment]
We could add a button that lets you input a url, and it'll extract the video ID from that, and change the page location to that music id. But we'd have to check if it's on youtube music first, because not all music videos are under the "Music" category. It's stupid, I know.

I'll try to implement this and see how it works out, and then I'll make a PR.

**Comment by KillerBOSS2019** [comment]
Added play-url to the restful API https://github.com/ytmdesktop/ytmdesktop/pull/845

**Comment by akabakass** [comment]
thx for your comments, sorry I didn't noticed the ytmd:// trick (as you say, broken for now) which could work. thanks also for the play-url implementation. will wait for next release to decide what to do

**Comment by dannlea** [comment]
I know this was mentioned as being fixed in the next release, but has it been released and broken again? I can't seem to make it work yet.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
