### ISSUE TITLE
Add Last.fm button to discord rich presence.

### ISSUE THREAD

**Issue by Vilsol** [ytmdesktop/ytmdesktop#917]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

It would be nice to have an optional feature where if you have linked your YTMD to Last.fm you could also enable it so underneath the "Play on YouTube Music" discord button would show "View my Last.fm".

**Comment by Alipoodle** [comment]
Going to leave this one open to a bit of Discussion for if people would like this... but personally I see this as a bit of our of scope for this project.
This is for YouTube Music, we including L.Fm stuff in our application because of a lot of people use it for Scrobbling, but not for sharing it out publicly, there should be other Rich Presences which can use Rich Presence of the Current L.FM song being Scrobbled.
