### ISSUE TITLE
Login button doesent work if a song is playing

### ISSUE THREAD

**Issue by LuccaRomanelli** [ytmdesktop/ytmdesktop#928]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

If you try to click the button to login with a music playing it does nothing

### Expected Behavior

I think if you clik login, it should stop the reproduction of the song and start the process of login

### Steps To Reproduce

Start a rendom song then try to login

### YTMDesktop

v1.13.0

### OS

Ubuntu 

### OS Version

20.4.2 LTS

### Arch

x86

### Installation way

ubuntu store

### Anything else?

It is not an urgent bug, but something that would be great for new user

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

This issue should be fixed :)
