### ISSUE TITLE
Queue image covers

### ISSUE THREAD

**Issue by Gratenes** [ytmdesktop/ytmdesktop#946]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When you fetch the endpoint http://localhost:9863/query/queue, the data given back does not supply the correct cover image
![opera_ZoeDk8AecC](https://user-images.githubusercontent.com/69170374/163661719-02f0bdf1-e396-41e4-a4b1-b9ddd5c39293.png)

### Expected Behavior

Expected to get dynamic images per song.

### Steps To Reproduce

1. Fetch the endpoint http://localhost:9863/query/queue
2. look at cover image

### YTMDesktop

1.14.1

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
Appears the Selector for images is broken, I cannot find it from my quick scan attempt now, but should be something easy to fix overall.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
