### ISSUE TITLE
User playlists, full queue etc. not protected behind password on API

### ISSUE THREAD

**Issue by TimTrayler** [ytmdesktop/ytmdesktop#947]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

If the user decides to enable the remote, anyone on the local network is able to get a list of all user playlists, the full current queue, network adapters, etc. without a password. This is private information and could be used for tracking and more.

### Expected Behavior

When the user protects the remote with a password all API routes should be locked just like the ```POST /query``` route.

### Steps To Reproduce

1. Enable the remote
2. Access information on ```http://localhost:9863/query/...```

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

winget

**Comment by Alipoodle** [comment]
As this is a Get Request this isn't intended as much to have it locked behind a Password on the API, but I agree that there's a decent bit of information being shared here which might be helpful.
As this is a very breaking change in regards to how the API is used, this may not instantly be implemented 

Ultimately, No one is REALLY going to use this as much of a means of tracking you, and it's information about the music you listen to, which isn't going to cause issues compared to something like Name & Email ETC.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

V2 of the API is greatly more secure. So this issue should already be fixed.
